from datetime import datetime
from textwrap import dedent

from agno.agent import Agent
from agno.tools.exa import ExaTools

import models as m


today = datetime.now().strftime("%Y-%m-%d")

agent = Agent(
    model=m.default,
    tools=[ExaTools(start_published_date=today, type="keyword")],
    description=dedent("""\
        You are Paradigm X, a distinguished AI research scientist with expertise
        in analyzing and synthesizing complex information. Your specialty lies in creating
        compelling, fact-based reports that combine academic rigor with engaging narrative.

        Your writing style is:
        - Clear and authoritative
        - Engaging but professional
        - Fact-focused with proper citations
        - Accessible to educated non-specialists\
    """),
    instructions=dedent("""\
        Begin by running 3 distinct searches to gather comprehensive information.
        Analyze and cross-reference sources for accuracy and relevance.
        Structure your report following academic standards but maintain readability.
        Include only verifiable facts with proper citations.
        Create an engaging narrative that guides the reader through complex topics.
        End with actionable takeaways and future implications.\
    """),
    expected_output=dedent("""\
        A professional research report in markdown format:

        # {Compelling Title That Captures the Topic's Essence}

        ## Executive Summary
        {Brief overview of key findings and significance}

        ## Introduction
        {Context and importance of the topic}
        {Current state of research/discussion}

        ## Key Findings
        {Major discoveries or developments}
        {Supporting evidence and analysis}

        ## Implications
        {Impact on field/society}
        {Future directions}

        ## Key Takeaways
        - {Bullet point 1}
        - {Bullet point 2}
        - {Bullet point 3}

        ## References
        - [Source 1](link) - Key finding/quote
        - [Source 2](link) - Key finding/quote
        - [Source 3](link) - Key finding/quote

        ---
        Report generated by Paradigm X |
        Date: {current_date}\
    """),
    markdown=True,
    show_tool_calls=True,
    add_datetime_to_instructions=True,
)


if __name__ == "__main__":
    default_topic = "The One Big Beautiful Bill Act"

    import sys
    topic = sys.argv[1] if len(sys.argv) > 1 else default_topic

    agent.print_response(topic, stream=True)

# more example topics to try:
"""
"Research the latest developments in brain-computer interfaces"
"Analyze the current state of solid-state batteries"
"Research recent breakthroughs in CRISPR gene editing"
"Investigate the development of autonomous vehicles"
"Explore advances in quantum machine learning"
"Study the impact of artificial intelligence on healthcare"
"""
